language: minimal

install:
  - source prepareenv.sh
  - source .github/travis/check_license.sh
  - source .github/travis/check_python_script.sh

script:
  - conda activate yosys-env
  - which tox
  - tox

notifications:
  email: false
