language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install tox
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install -q setuptools
  - conda update -q conda
  - conda env create --file conf/environment.yml
  - conda activate yosys-env

script: tox

notifications:
  email: false
