language: python

python:
  - 2.7
    env: TOXENV=py27
  - 3.4
    env: TOXENV=py27
  - 3.5
    env: TOXENV=py27
  - 3.6
    env: TOXENV=py27
  - 3.7
    env: TOXENV=py27

install:
  - source prepareenv.sh
  - source .github/travis/check_license.sh
  - source .github/travis/check_python_script.sh

script:
  - conda activate yosys-env
  - which tox
  - tox

notifications:
  email: false
