# Copyright (C) 2021  The Symbiflow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

name: v2x-docs
channels:
- symbiflow
- conda-forge
dependencies:
- python=3.7
- pip
- pycairo
- pango
- pygobject
- symbiflow-yosys
- netlistsvg
# ReadTheDocs dependencies (installed here but also by the docs build CI)
- mock
- pillow
- sphinx
- sphinx_rtd_theme
# Packages installed from PyPI
- pip:
  - -r file:requirements.txt
